title:   이성민
logo: /assets/img/teemo.jpg
email: sungmin1704@naver.com
description: 네이버 클라우드를 시작으로.
favicon: true
color-scheme: auto
remote_theme: vaibhavvikas/jekyll-theme-minimalistic

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

platforms: link
  - name: Sungmin
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/eellda
  - name: Cloud
    icon: <i class="fa-thin fa-cloud"></i>
    link: https://www.ncloud.com/
    name: Notion
    icon: <i class="fa-solid fa-layer-group"></i>
    link: 

navigation: History
  - name: Naver Cloud Stady
    link: 
    sublist:
      - name: Project
        link: ./index.html#small-image
  - name: Nothing Page
    link: ./another-page.html
