title: 　　이성민
logo: /assets/img/teemo.jpg
email: sungmin1704@naver.com
description: 네이버 클라우드를 시작으로.
favicon: true
color-scheme: auto
remote_theme: vaibhavvikas/jekyll-theme-minimalistic

search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# To disable support for mermaid diagrams (https://mermaid-js.github.io/mermaid/),
# comment out the `mermaid` and `version` keys below
# By default, consuming the theme as a gem leaves mermaid disabled; it is opt-in
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.6"
  # Put any additional configuration, such as setting the theme, in _includes/mermaid_config.js
  # See also docs/ui-components/code

# Enable or disable heading anchors
heading_anchors: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

platforms:
  - name: Sungmin
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/eellda
  - name: Cloud
    icon: <i class="fa-solid fa-database"></i>
    link: https://www.ncloud.com/

navigation:
  - name: Naver Clooud Study
    link: 
    sublist:
      - name: Project
        link: ./index.html#small-image
  - name: Nothing Page
    link: ./another-page.html
