title: 　　이성민
logo: /assets/img/teemo.jpg
email: sungmin1704@naver.com
description: 네이버 클라우드를 시작으로.
favicon: true
color-scheme: auto
remote_theme: vaibhavvikas/jekyll-theme-minimalistic

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

platforms:
  - name: Sungmin's Git
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/eellda
  - name: Naver Cloud
    icon: <i class="fa-solid fa-database"></i>
    link: https://www.ncloud.com/

navigation:
  - name: 2022년
    link: 
    sublist:
      - name: Cloud
        link: ./index.html#small-image
      - name: Linux
        link: ./index.html#small-image
  - name: Nothing Page
    link: ./another-page.html
