title: 　　이성민
logo: /assets/img/teemo.jpg
email: tree500253@gmail.com
description: 네이버 클라우드를 시작으로.
favicon: true
color-scheme: dark
remote_theme: vaibhavvikas/jekyll-theme-minimalistic

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

platforms:
  - name: Sungmin's Git
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/eellda
  - name: Naver Cloud
    icon: <i class="fa-solid fa-database"></i>
    link: https://www.ncloud.com/

navigation:
  - name: Academy
    link: 
    sublist:
      - name: Cloud
        link: /_posts/22-11-cloud.md
      - name: Linux
        link: ./index.html#small-image
      - name: Projects
        link: ./index.html#small-image

  - name: 2023
    link: ./another-page.html
